### ISSUE TITLE
Missing "priv/static/asset-manifest.json"

### ISSUE THREAD

**Issue by swistaczek** [CodingZeal/phoenix-react-apollo-demo#1]
First of all thanks for sharing this project ;)! It looks like great place to start hacking with phoenix and GraphQL. I have some trouble with running project, after installing deps (mix and npm) and running ```mix todo_app.setup```:

```
== Compilation error on file web/views/layout_view.ex ==
** (File.Error) could not read file "priv/static/asset-manifest.json": no such file or directory
    (elixir) lib/file.ex:244: File.read!/1
    web/views/layout_view.ex:5: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by lexun** [comment]
Hey @swistaczek, glad to hear you find it useful!

It turns out the app won't compile to run the setup task unless it's able to find that asset-manifest, and the setup task followed by `npm install` is supposed to be what generates it. Since I created it manually as I was setting up the project I didn't realize it was a problem, so thanks for posting the issue!

I'll get it fixed ASAP, but in the meantime you can manually do what that setup task is attempting: Create a file named `.env` in the root of the project with the content `BUILD_PATH=priv/static.` Once that is there you can `npm install` which should trigger a build and create the asset-manifest in the proper location. Let me know if that works, and thanks again for the heads up!

**Comment by swistaczek** [comment]
Thanks :)!
